package e

const (
	SUCCESS = 200
	ERROR   = 500

	ERROR_PARSING_CONFIG_FILE                     = 30001
	ERROR_GETTING_CURRENT_DIR                     = 30002
	ERROR_CREATING_KUBECONFIG                     = 30003
	ERROR_CREATING_CLIENTSET                      = 30004
	ERROR_CREATING_NAMESPACE                      = 30005
	ERROR_CONNECTING_DATABASE                     = 30006
	ERROR_SETUP_DATABASE                          = 30007
	ERROR_CREATING_PROJECT_WRONG_INPUT            = 30008
	ERROR_GETTING_PROJECTS                        = 30009
	ERROR_GETTING_PROJECT_NOT_INTEGER_PROJECT_ID  = 30010
	ERROR_GETTING_PROJECT                         = 30011
	ERROR_CREATING_ARTICLE_NOT_INTEGER_PROJECT_ID = 30012
	ERROR_CREATING_ARTICLE_NOT_EXISTS_PROJECT     = 30013
	ERROR_CREATING_ARTICLE_WRONG_INPUT            = 30014
	ERROR_GETTING_ARTICLES_NOT_INTEGER_PROJECT_ID = 30015
	ERROR_GETTING_ARTICLES                        = 30016
	ERROR_GETTING_ARTICLE_NOT_INTEGER_PROJECT_ID  = 30017
	ERROR_GETTING_ARTICLE_NOT_INTEGER_ARTICLE_ID  = 30018
	ERROR_GETTING_ARTICLE                         = 30019
)
